### ISSUE TITLE
Modifying <ANDROID_ROOT>/build/core/main.mk & <ANDROID_ROOT>/frameworks/base/data/etc/platform.xml

### ISSUE THREAD

**Issue by Pascal66** [munjeni/miui_sony_xperia#2]
Where can I modify the stockrom or rom before it's being created ?

**Comment by munjeni** [comment]
Sorry, not understand your question!

**Comment by Pascal66** [comment]
Sorry, I'll try explain :
I want to try to integrate [http://open-nfc.org/wp/2013/03/06/open-nfc-4-5-2-16234-including-android-edition-for-jb_4-2-1_r1/](url) the android port of opennfc.
I need to  have a full nfc working with my sola.
But I can't found a way to apply all the path in this muiui branch

**Comment by munjeni** [comment]
Sorry I can't help since I owned xperia go 2 years ago and realy I am not interested for novathor anymore! You can ask somebody on xda

**Comment by Pascal66** [comment]
I understand because I  follow you since 2013 on Xda, and never found  a good rom other than yours
thank you (i didnt find any cm9 to test with miui)
but with stockrom everything work (nfc ok but no wps )
