### ISSUE TITLE
formata data folder

### ISSUE THREAD

**Issue by Pascal66** [munjeni/miui_sony_xperia#4]
Sorry to bother you.
Where's the setting wich tell the installation to format the data folder ?
I need to build rom and avoid loosing data each time.

**Comment by munjeni** [comment]
Look into https://github.com/munjeni/miui_sony_xperia/blob/master/makemiui.sh below line "wipe data factory reset..."

**Comment by Pascal66** [comment]
:+1: Merci
I feel stupid lol
